# Generated by Django 5.2.5 on 2025-08-26 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content',
            new_name='body',
        ),
        migrations.AddField(
            model_name='page',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(default=1, upload_to='pages/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='subtitle',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
